-- Local dev seed data.
-- Plans, RLS policies, and other core data are already seeded by the migrations
-- in supabase/migrations/. Add local-only convenience data here if needed.

-- No admin account is bootstrapped here on purpose — a real, working
-- password used to be hardcoded in this file (committed to git in plain
-- text), which is exactly the kind of exposure the separate /admin/login
-- space and the public.approved_admins allowlist are meant to avoid. To
-- create a local admin after `supabase db reset`, run a one-off script
-- outside of any tracked file: insert the admin's email into
-- public.approved_admins, then either sign up normally through the app
-- (email confirmation applies) or insert directly into
-- auth.users/auth.identities the same way Supabase's Auth Admin API would.
-- Never commit a real credential to this file again.
